version: 2.1
jobs:
  testing:
    docker:
      - image: circleci/node:16.3.0

    steps:
      - checkout
      - run:
          name: Install validator
          command: |
            npm i html-validator
      - run:
          name: Run validation
          command: |
            node_modules/.bin/html-validate MyPage.html
      - run:
          name: Show version
          command: |
            html-validate --version
workflows:
  build_test:
    jobs:
      - testing 