version: 2.1
jobs:
  testing:
    docker:
      - image: circleci/node:16.3.0

    steps:
      - checkout
      - run:
          name: Install validator
          command: |
            npm i html-validator
      - run:
          name: Run validation
          command: |
            node_modules/.bin/html-validate "*.html"
      - run:
          name: Show version
          command: |
            node_modules/.bin/html-validate --version
      - store_test_results:
          path: test-results
      # Grab the file and attach them to the build to access in different way
      - store_artifacts:
          path: test-results
workflows:
  build_test:
    jobs:
      - testing 